name: Site Keep Alive

on:
  schedule:
    # Această linie face totul automat la fiecare 20 de minute, nonstop
    - cron: '*/20 * * * *'
  workflow_dispatch: # Asta e doar o opțiune de rezervă, nu te obligă la nimic manual

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Run bot
        run: python bot.py
